"""add column IVA to products table

Revision ID: d0c2d2dafaf5
Revises: bf7f7b90bbbf
Create Date: 2024-11-02 17:21:45.450000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0c2d2dafaf5'
down_revision: Union[str, None] = 'bf7f7b90bbbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('IVA', sa.Float(precision=2), nullable=False))
    op.alter_column('products', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=3),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.Float(precision=3),
               type_=sa.REAL(),
               existing_nullable=False)
    op.drop_column('products', 'IVA')
    # ### end Alembic commands ###
